using Microsoft.VisualBasic;
using System.Reflection.PortableExecutable;
using System.Resources;
using System.Security.Claims;
using System.Threading;

namespace Regions
{
    internal class Regions
    {
        static void Main(string[] args)
        {
            #region Self Study and Notes

            /* Start *****************************************************************************************************************/

            // use [Authorize] attribute without specifying a schema

            /* End ******************************************************************************************************************/

            #endregion


            #region Starting with Security Module (using Identity package of Microsoft)

            /* Start *****************************************************************************************************************/

            // Authentication : The process of determining a user's identity 
            // Authorization  : The process of determining whether a user has access to a resource (through Roles)

            // In case we don't have roles , then Authentication is the same as Authorization


            // For more info check session * MVC 

            // 1 - Install the package in project "core" -> identity.EntityFrameworkCore
            // 2 - What are the entities in Security Module ? -> User and Role ... We will not use the identity user class provided by the
            //     package , but we will use our custom made classes (inherit from identity user) class is 'ApplicationUser'
            //     (found in core project -> entities -> Identity) , and we will use the default identity role class
            // 3 - We will have another database for the security (Identity Folder in Repository project) , and add migrations
            // 4 - Data Seeding (one user to test the login before implementing the Register)
            //     Note : Don't forget to register the services wanted .... 

            /* End ******************************************************************************************************************/

            #endregion


            #region Login and Register Controllers

            /* Start *****************************************************************************************************************/

            // Nothing to Say ! 
            // See AccountController , UserDTO , LoginDTO , RegisterDTO and the program class 

            /* End ******************************************************************************************************************/

            #endregion


            #region Generating Tokens , Using JWT

            /* Start *****************************************************************************************************************/

            // Important : https://jwt.io/

            // The Token is an incrypted string that is generated by a security algorithm based on some inputs and the security key 
            // Why we use Tokens ? So that not every time the user send the request then he must send the username and password ! 
            // The user only sends the username and password and login , when logged in he takes a 'Token' That we use to know that he is 
            // a valid user 
            // The token is in the Header of the 'request' , and when the request is sent to the backend , the server checks if this is
            // a valid token or not (Generated by the server and lifetime is not expired)

            // JWT : JSON Web token , the inputs that are used for generating the token is in type 'JSON'

            // Ex : 
            // Encoded Token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDI
            //                 yfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c 

            // Decoded Token (3 components , seperated by dots) : 
            // 1 - Header (Algorithm & Token Type) -> It's a JSON , consists of two parts: the type of the token, which is JWT, and the
            //                                        signing algorithm being used, such as HMAC SHA256 or RSA.
            // 2 - Payload (Data or Claims) ->  It's a JSON , used for validation that they are the same data used for generating the token
            //     - Claims can be one of three types : 
            //         1 - Registered Claims (Pre-defined) : same for all people that will take the token (ex:subject , audience , issuer , .. )
            //         2 - Private Claims : Differes from one user to another (ex: name , salary , .. ) , used for information exchange ,
            //                              means sending data (we must not send critical data here ... )
            //         3 - Public Claims : Self study
            // 3 - Verify Signature -> here we call the security algorithm , takes the Header and Payload (header and payload must be
            //                         converted to base64 encoded) , and takes also the Security key (make complex as we can .. )



            // Payload from DOCS : 
            // 
            // The second part of the token is the payload, which contains the claims. Claims are statements about an entity(typically,
            // the user) and additional data. There are three types of claims: registered, public, and private claims.
            //
            // 1 - Registered claims: These are a set of predefined claims which are not mandatory but recommended, to provide a set
            //                        of useful, interoperable claims.Some of them are: iss(issuer), exp(expiration time), sub(subject),
            //                        aud(audience), and others.
            // 
            // 2 - Private claims : These are the custom claims created to share information between parties that agree on using them
            //                      and are neither registered or public claims.
            //
            // 3 - Public claims : These can be defined at will by those using JWTs. But to avoid collisions they should be defined in
            //                     the IANA JSON Web Token Registry or be defined as a URI that contains a collision resistant namespace.
            // 






            // When should you use JSON Web Tokens?
            // 
            // 1 - Authorization: This is the most common scenario for using JWT.Once the user is logged in, each subsequent request will
            //     include the JWT, allowing the user to access routes, services, and resources that are permitted with that token. Single
            //     Sign On is a feature that widely uses JWT nowadays, because of its small overhead and its ability to be easily used across
            //     different domains.
            // 
            // 2 - Information Exchange: JSON Web Tokens are a good way of securely transmitting information between parties (backend and
            //     frontend). Because JWTs can be signed—for example, using public/private key pairs—you can be sure the senders are who 
            //     they say they are. Additionally, as the signature is calculated using the header and the payload, you can also verify 
            //     that the content hasn't been tampered with.

            // ---------------------------------------------------------------------------

            // Building the service that we will use to generate the token : 
            // 1 - Add the first contract (interface) in the core project , in Service Contracts (till now contains only signature for
            //     function that will be used to create the token)
            // 2 - Add Folder in project 'Service' called 'AuthService' , and make a class that implements that interface 
            // 3 - adding claims , why we add claims ? for information exchange , means that we put data inside the auth header instead of
            //     making an endpoint that returns this data 
            // 4 - Making the Security Key , First install the package 'Microsoft.AspNetCore.Authentication.JwtBearer' 
            // 5 - Making the token object that we will use to create the toke , and provide the Registered Claims in it
            // 6 - return the token by the from the function 


            // now refactor login and register endpoints to work with tokens (don't miss allowing DI for services in the Program class)


            // Notice now when logging in , a token is provided in the response 


            // Now we must select the endpoints that the user must be authorized and authenticated to use them ... we will take for example
            // the 'GetAllProducts' endpoint in the Products controller
            // 1 - [Authorize(AuthenticationSchemes ="Bearer")] attribute above the endpoint + providing the challenge schema
            // 2 - The token is set in the header of the request , "Authorization Header"
            // 3 - in the program class : 
            //
            //        webApplicationbuilder.Services.AddAuthentication()           
            //            .AddJwtBearer("Bearer", options =>
            //             {
            //                 options.TokenValidationParameters = new TokenValidationParameters()
            //                 {
            //                     ValidateIssuer = true,
            //                     ValidIssuer = webApplicationbuilder.Configuration["JWT:ValidIssuer"],
            //                     ValidateAudience = true,
            //                     ValidAudience = webApplicationbuilder.Configuration["JWT:ValidAudience"],
            //                     ValidateIssuerSigningKey = true,
            //                     IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(webApplicationbuilder.Configuration["JWT:AuthKey"])),
            //                     ValidateLifetime = true,
            //                     ClockSkew = TimeSpan.Zero
            //                 };
            //             });
            //    Note : If we didn't specify the "Bearer" shcema then this configurations is for the default schema "Identity.Applicaton"



            // now when using postman to test the endpoint of GetAllProducts , add a header "Bearer kjsdfjkhadbadnabdskgj" (Bearer + token)
            // OR
            // in the authentication , beside headers .. add a "Bearer Token" and paste the token we have .. it's the same as adding an 
            // authentication header



            // Challenging schema : every endpoint that uses the "Authorize attribute" has the challenge schema (ex: Bearer)

            // With every endpoint , we must specify the challenge schema ... ex: [Authorize(AuthenticationSchemes ="Bearer")] 
            // Unless we make a default challenge schema : 
            // in the program , when adding Authentication as a service , this function has two overloads 
            // first overload : Specify the default schema that we will configure it's handler
            // second overload : takes action of one parameter , and then we can configure the default challenging schema 

            // Important Note : First configure middlewares app.UseAuthentication() and app.UseAuthorization() then it will work !
            //                  THEY MUST BE AFTER " app.MapControllers() "


            /* End ******************************************************************************************************************/

            #endregion


            #region Setup Token Variable in Postman (Postman Script)

            /* Start *****************************************************************************************************************/

            // Notes: Variables can be among all the workspace or among the collection only
            //        To make a variable -> click on the collection -> variables -> add and edit the variables
            //        To use a variable -> {{ variable name }}


            // instead of copying and pasting the Token every time we send the request to the server , we can save the token in a 
            // variable (as we discussed before ...)

            // But in case the token expires or we use refresh tokens (the valid token changes every second) , then it's impossible to 
            // change the value of the variable manually , so we can write a Postman Script to automatically take the new Token and 
            // set the variable with it automatically in every change of the token 

            // How to write a Postman Script ? 
            // in the login request in postman , in "Scripts" Tab beside "Headers" and "Body" , in post-response .. write the script here ,
            // Copy paste from google ,,, The Script : 

            // const User = pm.response.json();
            // pm.test("Has properties", function(){
            //     pm.expect(User).to.have.property('displayname')
            //     pm.expect(User).to.have.property('email')
            //     pm.expect(User).to.have.property('token')
            // });
            // 
            // if (pm.test("Has properties"))
            // {
            //     pm.globals.set('', User.token);
            // }

            /* End ******************************************************************************************************************/

            #endregion


            #region Some Endpoints (wanted in Frontend)

            /* Start *****************************************************************************************************************/

            // 1 - Get Current Logged In User : inside the account controller ...
            // 2 - Get Current User Address : (notice that the navigational property data is not loaded !!!)
            //                                (notice the problem of Self Looping with Bi-directional Navigational Property)
            // 3 - Update User Address : inside the account controller ... (notice getting the object with tracking )
            // 4 - validate Duplicate Email : and then use it inside the "Register Endpoint" , don't miss using .Result with async code ...


            // The problem of Self Looping with Bi-directional Navigational Property can be solved with 3 solutions : 
            // 1 - [JsonIgnore] attribute  : incase we don't want to load the navigational property data from one direction , then use 
            //                               [JsonIgnore] attribute above the Navigational Property that we don't want to load it's data 
            //                               when serializing the response to JSON.
            //                               not recommended , because in the class we don't want to write any thing except the properties
            // 2 - AddressDTO : using DTO as a return type and ignoring the Navigational Property 
            // 3 - Installing package "NewtonsoftJson" : if we want to solve the problem with keeping the Bi-directional Navigational
            //                                           Properties then install the package "Microsoft.AspNetCore.Mvc.NewtonsoftJson" , 
            //                                           and in the program classs , when "webApplicationbuilder.Services.AddControllers();"
            //                                           add the extension method ".AddNewtonsoftJson(options => { .. })" and configure it


            // We will not use the third way in the previous scenario , but we configured it already

            /* End ******************************************************************************************************************/

            #endregion
        }
    }
}
