// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using NorthWindConsole.Entites;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace NorthWindConsole.Context
{
    public partial interface INorthwindContextProcedures
    {
        Task<int> DeleteProductByIdAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<TenMostExpensiveProductsResult>> TenMostExpensiveProductsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateProductPriceAsync(int? id, decimal? newPrice, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
