using System.Reflection.Metadata;

namespace My
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // Syntax sugar : write less code , compiler generates other code ! 
            // if we checked "Do not use top level statements" when creating the project :
            // - We then will have a namespace , class , main function 
            // if we didn't check "Do not use top level statements" when creating the project :
            // - We will not have a namespace , class , main function ... but if we see the IL we will find that they 
            //   will be generated by the compiler 


            // All built-in numeric datatypes => Value type datatypes 

            // Remember : promotion rules (ex: int/int => int , double/int => double , .... )

            Console.WriteLine(7);   // the compiler sees the "7" as the smallest datatype that can hold this value (starting from int), 
            //                      // smaller like (short , byte , ... ) are out of selection here , only (int , uint, long , ulong )

            // discard : for more readable numbers : 
            // 2_000_000_000      ==> discarded by the compiler 


            Console.WriteLine(13.5);  // here the compiler sees it as a double

            // float f = 13.5;    // Error 
            // so this may have an overflow so the compiler gives an error and we must put it inside a double or explicit casting ! 

            // Casting : 
            //
            // literal casting : (f for float , m for decimal)
            float ff = 13.5f;


            // double VS decimal : differs in the persision "number of digits after the point"
            // decimal has the largest number of digits after the point 

            decimal d = 15000.23M;


            // explicit casting : 
            int a = 10;
            long b = 1000;
            // a = b;         // Compilation Error , requires explicit casting , unsafe casting , narrowing
            a = (int)b;       // now we may have an overflow as int cannot hold long values , No errors , but getting bad data ! 
            b = a;            // valid , widening , implicit casting happened , safe casting 

            // The CLR by default don't throw runtime error or exception when having an overflow ! 
            // if you want it to throw an exception then we must use a "checked" block (Note: also we have "unchecked" block)

            // checked block : instruct the CLR to fire and throw an exception when having an overflow 
            //                 exception : System.OverflowException 

            // Note : these exceptions must be cought by the developers (try catch .. discussed later)

            // What about the "unchecked" block ? 
            // it's used if we don't want to check on some code INSIDE THE "CHECKED" block !! 
            // this is used to avoid closing the checked block and opening another one 


            long l = long.MaxValue;
            int x = (int)l;             // no errors , the data is damaged

            checked
            {
                x = (int)l;             // runtime error , because we are in a checked block 
            }


            // note : int , long .. are structs , they have an attribute for getting max and min values 
            // ex: 
            // int.MaxValue
            // int.MinValue
            // long.MaxValue
            // long.MinValue



            // implicit typed local variable : using keyword "var"
            // - C# is statically typed language , we must specify the datatype of the variable and stick with it (cannot change)

            double r = 13.4;
            Console.WriteLine(r.GetType().Name);

            // r = "Hi";          // Error , it's double and cannot be changed later after declaration ! 

            // so this will be visible in the next sessions when we have new large number of types (ex: with LINQ)
            // it's better to use "var" and the compiler will automatically know the type ! 
            // Note : this can be shown in ILSpy also 
            
            var v = 15.44;      // known as double automatically by compiler and cannot be changed later also ! 


            // default values for datatypes :
            // if i have a variable and i want to give it the default value but i don't know it ! 
            int t = default(int);     // old way specifying the type 
            int m = default;          // old way specifying the type 

            // default values : 
            // int => 0 
            // bool => false
            // double => 0.0 
            // reference types (class, string, object , .. ) => NULL 


            // Nullable datatypes : 

            // int x;
            // x = null;            // invalid 

            // value types which are stored in the stack cannot hold null (this what we know)
            // new : value types can hold null (ex: usefull when reading from database, can use old ways to solve this problem but
            //       this is easier)

            // Self study : how is nullable value types stored in the memory ? 


            // int? x = 10;  
            // x = null;     // null is a valid value

            // bool? b ;     
            // nullable bool can hold 3 values not 2 as a normal bool (gender = male OR female OR none) => nullable bool

            // this can be also with user defined structs , ex: nullable struct Employee 

            // remember : implicit casting and explicit casting with nullable and non-nullable value type datatypes 
            //            who is narrowing and who is widening 

            // to write protective code (safe code) with nullables : 
            // use => 
            // 1 - try catch => costly way to handle exceptions ! 
            // 2 - use if else .. 
            // 3 - properties and methods : 
            //       - .HasValue  => returns bool 
            //       - .Value     => returns the value , Note : muse be checked first that it HasValue , otherwise Exception  
            // 4 - using null coalese operator =>  int y = x??-1;  => means if is is not null then put x , else if x = null then put -1
            // 5 - int y = x.HasValue ? x.Value : -1    => Ternary operators


            // we may have many warnings , that's because the nullable reference type valuetypes (remember them)

            // null propagation operator
            // for(...; i < Arr?.Length ;...)
            // this is good , as it the array refers to null => will not go inside the loop , if it's Arr.Length then Exception

            // Arr.Length      => int
            // Arr?.Length     => int?

            // Arr?.Length??-1 => int

            // Note : see the IL code , it's written without this syntax sugar => using if and && and other ... 

            // null propeagation operator is used heavily when: 
            // Employee e = new();
            // e?.Department?.Name?.Length??0


            // boxing and unboxing 

            // ref to base = derived    (no problem, safe and implicit, if the derived is valuetype then this is called boxing)
            // reference types ARE NOT IN STACK 
            // Note : if the derived is a reference type then this is not boxing or unboxing

            // boxing is safe but time consuming

            // unboxing => derived = base 
            // unsafe and must be done explicitly

            // -----------------------------------------------------------------------------------------

            // Part 2 : 

            // we can define datatypes in other assemblies (other projects , then we can reference the other project)
            // when adding a project reference , we can see in the bin/debug folder that we have a file there which is the name of the 
            // project .dll , this is the reference , so when deployment , the project reference .dll will be there 


            // working with structs : 

            // Point struct 
            // Point p1; 
            // Allocate 8 bytes in the stack (uninitialized)

            // p1.Show();    // cannot do that before initialization
            // 
            // we must first initialize the object by the ctor 


            // in structs (maybe 2 releases before) , it was a MUST to initialize all the members in any user defined ctor
            // not it's not important as the compiler gives the attributes initial values = their default values

            // in structs : new is for "Constructor Selection" ONLY

            // Point p2 = new Point(); 
            // Allocate 8 bytes in the stack, use new to choose the ctor that will initialze the attributes
            // 

            // Note : we can write (x=y=100) to initialize both !
            // 
            //

            // Note : now in structs , compiler will generate a empty parameterless ctor with initializing all members with the
            //        default values (unless we made it)
            // Note : also before some C# versions , we couldn't make the empty parameterless ctor ever ! 

            // Now : it's not a must to give all of the member initial values , when not giving for a member any value in the ctor 
            //       then the compiler initializes it by the default value 

            // So now to sum up : if we made a ctor and we didn't iniitilze all the members then the compiler will initialze them and
            // we can see this inside the IL code (compiler will ensure that all members are initialized before exiting any ueer-defined
            // ctor. )
            // So always I have a parameterless ctor (with structs) , but in reference types if we defined a ctor then the default 
            // parameterless will not be there and we must write it.

            // starting from C# some version we can make the parameterless ctor , old we cannot do this 

            // Note : we can use the ctor of int struct =>
            // int x = new int();

            // self study : 
            // - ref struct
            // - how equals and gethashcode works in C#


            // Enums : 
            // in the memory we don't save the label of the enum value , but we save the value for it (int value)
            // it's a decoration for a int values

            // EnumName x = (EnumName) 4;        // must cast 
            // EnumName x = (EnumName) 10000;    // must cast , but if not having a value then will print the number => 10000

            // enum FCAI { A = 2 , B = 5 , C , D = 101}     // we have value = 1, 5, 6 for C , 101  ... ONLYYY 
            // enum FCAI : int {  ......  }                 // values are of type int, if we don't need then make it a smaller value
            // Note : int is the size of the struct variable now

            // the same label cannot be repeated , but the same value can be repeated for more then one label

            // Note : EnumName x = new();     // then the value is 0 , corresponding to a value or not , no problem 


            // ----------------------------------------------------------


            // Now we can make the one variable have more than one value inside it , but manipulating it's bits
            // search => Bit flag array , the one byte can hold multiple flags , each byte for a flag ... this is better than 
            //           making 8 bytes and for loop on them to manipulate any of the flag


            // This can be done with the Enum here also but when making the values of the labels as (1, 2, 4, 8, 16, .... )
            // now it's a bit flag enum or bit flag array ! 

            // read=1, write=2, update=4, delete=8


            // when giving you a value don't see it as a value without label , but use flags and see them what bits are corresponding to
            // the labels in the values ? 

            // add [Flags] attribute over the enum to do that 

            // when seeing 8 and 4 we will not see 12 , but we will see the labels corresponding to the sum of them 

            // Permissions p = Permissions.Read;
            // p ^= Permissions.write;       // if not [Flags] then 12 , if [Flags] then read , write ! 

            // p = (Permissions)0x0F;        // all of them , grant all ----> write , read , delete , update
            // p = (Permissions)0x00;        // all of them , revoke all 
            // 

            // we can also make it like this : 


            // Enum Permissions {read=1, write=2, update=4, delete=8, Root=15, SuperUser=0b_0000_1110}
            // Self study : 0x0F , and other writings ... 

            // p = (Permissions)0x0F;        // all of them , grant all  ----> Root 

            // if(p==Permissions.read)
            //     cw("YES");
            // else 
            //     cw("NO");

            // will be false because it has many labels ! return true only when the p = read only !! 

            // to make what we want we must use : 
            // if((p&permissions.read) == permission.read)   // now works fine ! 


            // Switch case : it's better than if, it's constant time
            // if we see the IL , we will see that the switch case it converted to a jump table , we we jump to the matched case directly
            // switch can work with strings in C# , but performance wise it works different than numerics (int, short, long)
            // self study : does switch work with float , double in C# ??? 

            // note : break is not optional here !! it's mandatory (in all cases other than using "goto" discussed next lines ) , so
            //        there is no fall into or fall through so any case or default must have break .

            // to make more than one case with the same body =>
            // case 2: 
            // case 3: 
            //    cw("yes");


            // so how to make same "fall into or fall through" in C# => using "goto" (bad , violates every thing !)
            // it has th same performance but with a more less code 
            // self study : where goto can be used in C# ? 

            // case 1: 
            //      cw();
            //      goto case 2;
            // case 2: 
            //      ........
            //      ........


            // switch case with strings : 
            // some times switch is made as if else , this happens when the number of cases is small (5 or 6 or 7 don't remember)
            // that's because of the overhead of making the jump table and a hashtable for strings (overhead)
            // can be seen in the IL when "build for release"

            // self study : strings with switch case and fat arrow (switch expression)
            // self study : pattern matching with switch 

            // by default the name of the namespace is the same name of the project name

        }
    }
}
