namespace My
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // sending by reference and by value for "reference types"

            // when sending by ref , it's like giving an alias name for the actual variable 

            // Note : self study , returning by reference

            // object initializer (only can be used with a public property or a public attribute)
            // Employee E = new() {id = 1, name = "mahmoud"}
            // this is used instead of manually changing each attribute , ex: E.id = 1; E.name = "mahmoud"

            // Note : VS can create for us ctors, properties, ... using Quick Actions , that shows when the mouse cursor is on the class or
            //        the attribute

            // self study : public attribute , and private set , what is the result ? or internal get , .. 

            // Classes : if we gave the attribute/property an initial value, this line will be the first line in the ctors after that.
            // Structs : if we gave the attribute/property an initial value, this will not work !
            // ex: public int Salary = 8000;      // class will work , struct will not work

            // property {field = ...............}
            // property {get {}  init{}}
            // property public required string name {get; set; }
            // property saflkasfkamsf {get; set;} = 5 

            // automatic property : 
            // public decimal Salary {get; set;}

            // when using automatic property we actually in the IL have an autogenerated backing field that is defined by the language , 
            // the get and set are dealing with this backing field.
            // Now : inside the class or struct we have only the property , and we cannot use the hidden attribute directly ! 

            // so automatic property is used to make the development faster , it's slower abit because of not using the attribute directly

            // read only property : with get only .. 

            // automatic property in C# 14 : we now could deal with the backig field using keyword "field" (valid only with auto property)
            // public decimal Salary {get; set{ field = value > 8000 ? 8000 : value ; }}


            // get only : can be initialzed only in the ctor or in the attribute it self when defining it in the class/struct
            // get init : can be initialzed only in the ctor or in the attribute it self or in the object initializer {....}

            // the attribute when making it a full property can be "readonly" written the first word
            // the attribute when making it a full property can be "required" written the first word
            // Note : required must have an initialization in the ctor or in the object initializer

            // what if working with the full property ? 
            // public required string name {get; set;} 


            // required can change , but init cannot change after initialization


            // primary constructors : feature in the class or struct or Record (discussed later)
            // used in early phases of development or when transfering the data (DTOs , discussed later)
            // outside the class we cannot deal with id, name, salary , but inside the class we can use them and make functions and prop
            // public class Employee(int id, string name, decimal salary)
            // {
            //      public string GetName {get {return name;}}
            // 
            // }

            // the only constraint with the primary ctor is that when making a user defined ctor then we must chain on the primary ctor
            // public Employee(int _id):this(_id, " " ,8000)




            // try catch finally 

            // when entering data that is not valid casting or parsint , we have a System.FormatException ... 
            // when an exception occures (runtime error) the CLR stops the normal execution of the program , an object of the exception
            // type is created and thrown , we can catch this using try catch finally or it will be thrown on the user and stop execution
            // of the program ! 

            // Note : using try catch finally is a costy process due to stopping the normal path of the execution and also creating
            //        objects , so we must use it when we actually need it 

            // try , [ then (0 or 1 or 2 or 3 or more catches) , then (0 or 1 finally) ] (one of them(catch,finally) is mandatory)
            // each catch can have a specific type of the exception catch(DivideByZeroException ex){ .. } , catch(FormatException ex){ .. }
            // note : important to put the catches in a right ordering , and if all catches doesn't match the exception type that is thrown
            //        then the program will stop ! so make sure to have the parent class "Exception" as the last catch exception type or 
            //        "somewhere" , means that we may have try that has a function call inside it , and that function handles some exceptions
            //        so the outer try that must handle the other types of exceptions.
            //        ex: try{ Func(); } catch{ remaining exception types here } 
            //            Func(){ try{some code} catch{some exception types here}}
            //        Note : if an type of unhandled exception occured in the function then the remaining of function will NOT be executed.

            // - if no errors in the try : finally if exists is executed, normal code path 
            // - if error in the try line 15 for example : try line 16 till end of try NOT EXECUTED , catch that catches the specific
            //   type of exception is executed , finally if exists is executed , normal code path 
            // - when catching an error and an error also occured in the catch , then the whole program will stop and finally will NOT exec


            // Note : we can write catch like this without the object , we now cannot use the object data and this is an object from the 
            //        general exception 
            //           try
            //           {
            //           }
            //           catch   // general System.Exception , and we don't have the object so we cannot know the data inside the obj ex
            //           {
            //           }

            // The best practice in the catch is to log the exception , and don't make lots of work

            // Note : VS has a window called "Exception settings" , that we can specify when to stop in the dubugging mode 

            // note : see the Exception class and it's properties and the types that inherit from this class.

            // ex.Message => this shouldn't be shown to the user , as it may have sensitive data 


            // what about the finally ? 
            // if we have importnat code that must be executed in ALL CASES (when no exceptions , exception that is handled, and the most
            // important when having an unhandled exception or error in the catch 'this is the difference between finally and other code
            // after try catch')

            // making our own exception : make a class that inherits "Exception" class , this class has a ctor that chains on the ctor
            //                            of the base and we may change the message of the exception ... once we inherited from the 
            //                            exception class then we now can throw an object from this class or catch it also (the CLR will
            //                            not throw it , we must throw it if we want)

            // the exception must be a truly unexpected behaviour , so then we will use try catch with it .. but in the most cases 
            // we can handle the ex without try catch by using if or other some definsive and protective code
            // ex: (if y!=0) // Don't divide on Zero 


            // one of the ways to avoid using "try catch" : 
            // .TryParse() => return true or false ,  true if the parsing succeeded , and false if there is problem with parsing
            // bool flag = int OR double OR floag OR ... .TryParse(Console.ReadLine() or any string or any thing , out int num);
            // so this can be put into a while or do while loops


            // -------------------------------------------------------------------------------------------------------------
            // -------------------------------------------------------------------------------------------------------------

            // Part 2 : 


            // classes and their Ctors
            // IN CLASSES : 
            // if we didn't define a ctor , then the CLR will create the empty parameterless ctor, but if we wrote any ctor with any 
            // signature (it's user defined) then the compiler will no longer generate the empty parameterless ctor
            //
            // IN Structs : always there is an empty parameterless ctor

            // Note : boxing and unboxing happens only incase using a value type (struct) , not a reference type (class) 

            // how to make an object with the same state and data of another object ? 
            // obj1 = obj2;   // wrong reference equality 
            // - solved by deep copy through : 
            //    - copy ctor
            //    - .clone method (implement the IClonable interface) => discussed later

            // copy ctor : 
            // public Point(Point obj) { X = obj.X; Y=obj.Y;  }
            // in the main : Point P2 = new Point(P1);
            // in C++ , we used the copy ctor in 3 places (remember : related to passing an object by value type) .. this is not valid 
            // in C# as classes are reference types 

            // self study : copy ctor with struct in C# 

            // we don't have a global variable or attribute in C#.

            // static variables : 
            // object attribute (non-static) vs class attribute (static)
            // it's a class attribute , has the same value for the whole class , shared between all the objects
            // the static variable is accessed with the Class name , NOT the object itself.

            // public static int counter;                               
            // the getter or the property will also be static : 
            // public static int Counter { get{ return counter;}}       // it's readonly .. 

            // Note : Static attribute is always in the heap (even it's a value type) , it's initialized by the default value , it's 
            //        loaded in the heap when first using of the class .. so that it's not important to make an object from the class 
            //        to use the static variable

            // we also have a static property , static function (they are for the whole class not a specific object).

            // so in C# we have the option only for making object function (non-static) vs class function (static) 
            // remember in C++ we had another type of function "standalone function" , that is not here in C# (some workarrounds)



            // Discussing "this" : 
            // in the memory , do every object has the all set of function ????? 
            // Actually NO , this is repeating for the all set of functions with the number of objects of this class , instead we use "this"
            // It was a pointer to the caller object in C++ , but in C# it's a referece to the caller object. 
            // in the main function : 
            //    P1.SetX = 100; 
            //    // this is actually : 
            //    // Point::SetX(P1,100);
            // so the function is now static function that has an additional input parameter that is a reference to the caller object
            // in the class : 
            // public void SetX(int x){ X = x; }
            // the code in the Native : 
            //    // public static void SetX(Point this, int x) { this.X = x; }

            // what about the static method ? 
            // It doesn't have a "this" , so that we cannot "directly" access the members of the object 
            // note : "directly" means inside the function => X = _x , Y = _y ; ..... this is not valid but we can create a new object and
            //        use X and Y of the new object 


            // Note : the static can be used inside the class without any problems .. 

            // now operator overloading : MUST BE DONE WITH STATIC METHODS ONLY (in C++ it was a standalone or object method only ... )
            // Note : operator overloading is a language feature that is found in some languages (C++, C#) but not found in others (Java)
            // Note : In C# , we have some non-overloadable operators (ex:   "."    "=>"     "new"     "=" (assignment operator))
            // Note : In C# , if we overloaded the "+" then the "+=" is automatically overloaded
            // Note : In C# , we have cannot explicitly overload compound operators (ex: += , -= , .... )
            // Note : In C# , unary operators (++ , --) there is no difference in the implementation of them as prefix or postfix , it's 
            //        handled by default "BUT DON'T CHANGE IN THE INPUT PARAMETER !!"
            // Note : In C# "WITH COMPARISON OPERATORS ONLY (== , != , < , > , <= , >= , true , false)" it's a must to overload the two opposits of the
            //        operator because they come in pairs
            // Note : in C# , for casting operators , we must specify if it's explicit or implicit and NO RETURN TYPE , return type is
            //        replaced with the keyword "explicit" or "implicit" .... It's better to make all casting operators as explicit to 
            //        avoid problems and if we want to cast them cast explicitly.
            // Note : In C# , we have operator overloading for "true" and "false" (if (true) ... else ... )

            // public static Point operator + (Point left , Point right)
            // {
            //      return new Point(){X = left.X + right.X , Y = left.Y + right.Y};
            // }
            // public static Point operator + (Point left , int num)
            // {
            //      return new Point(){X = left.X + num , Y = left.Y + num};
            // }
            // public static Point operator ++ (Point obj)            // handle both prefix and postfix
            // {
            //      return new Point(){X = obj.X+1, Y = obj.Y+1};
            // }
            // public static bool operator == (Point left , Point right)
            // {
            //      return left.X  ==  right.X  &&  Y = left.Y  ==  right.Y ;
            // }
            // public static explicit operator string (Point obj)   // explicit :    string s = (string)P1; 
            // {
            //      return $"{X},{Y}";
            // }
            // public static implicit operator int (Point obj)      // implicit :    int x = P1;   or also   int x = (int)P1; 
            // {
            //      return (x+y)*100;
            // }
            // public static bool operator true  (Point obj)         // must have the opposite complementary
            // {
            //      return (obj.X != 0) || (obj.Y != 0) ;
            // }
            // public static bool operator false (Point obj)         // must have the opposite complementary
            // {
            //      return (obj.X == 0) && (obj.Y == 0) ;
            // }

            // we can make operator overloading also between 2 user defined types : 
            // in any class of the two : 
            // public static explicit operator Employee(Person P){ return new Employee() {EmpId = P.PID, AnualSalary = P.Salary*12 }; }


            // we can use static functions also inside a utility class or a helper class , that these functions doesn't depend on the 
            // object state (attributes and fields) .. and in this case also we can put static members inside a static class , this class
            // cannot be inistantiated , and functions inside a static class must be all static , that are called with the class name. 

            // Remember : inside the static function we cannot use a normal attribute , this attribute must be static also , and to 
            //            initialize this static attribute (once per class lifetime) so it's not a good option to initialize it in the 
            //            default ctors as this is called "reseting" and requires creating an object (which is not important incase of
            //            using static funtions , and not applicable incase of static classes.)
            //
            // So we have a "Static Constructor" static ctor :  executed one time per the class lifetime , before the first use of the
            //                                                  class (before using a static method from the class, before declaring an
            //                                                  object from the class , before using a static property in the class, .. )


            // static ctor : 
            // same as the ctor but with static keyword before it ,
            // Note : we CANNOT specify an access modifier or input parameter (must be parameterless) for a static ctor.
            //        And Max we can have 1 static ctor in the class
            //        And it's thread safe (discussed later)
            // static ClassName() { ... } 



            // we can write : will make a backing field, static ctor + init , getter => 
            // - public static double PI {get;} = 3.14;    // as an automatic property
            // instead of all this code : 
            // - static double PI; 
            // - static Ctor() { PI = 3.14;}


            // static class : container for static members , no non-static ctors , no non-static methods or attributes , this cannot
            //                be inherit from it , or inherit from other class inside it , and cannot be instantiated .
            //                ex: public static class MathFunctions { public static int Add(...) { .. } .... } 



            // Singleton Design Pattern : Class that we want to have only one instance in the whole program , control the instantiation , 
            //                            so we can have multiple references to the same object
            // Ex: see the class "GraphicsEngine"


            // Note : using square brackets is the new way for initializing array, list , ... 
            // int[] arr = [1,2,3];


            // self study : equality within classes how it works
            // self study : "this" in case of structs in C#
        }
    }
}
