using Microsoft.EntityFrameworkCore;
using NorthWindConsolApp.Context;

namespace NorthWindConsolApp
{
    internal class Program
    {
        static void Main(string[] args)
        {
            using NorthwindContext context = new();


            // Part 1 : here and Windows forms application : 

            // What if i have the database and i want to make the code ? 
            // - Reverse Engineer (Scaffolding)

            // command : Scaffold DbContext (with some additional info , connection string , tables , ... )
            // using UI : Add-on for VS called EF Core Power Tools
            //            Extensions -> Manage Extensions -> Browse -> "EF Core Power Tools" -> Install -> restart VS
            //            after restarting VS -> right click on the Project -> EFCore Power Tools
            //            good for using the SPs which are in the DB , and usefull when "reverse engineering"


            // starting with Reverse Engineer (Scaffolding) using EF Core Power Tools : 

            // choose the project -> right click -> EF Core Power Tools -> Reverse Engineer 
            // add connection to the SQL Service with specifying the Specific database we will work with 
            // now loads and choose the Tables , Views , SPs (views are same tables but with some different configurations)
            // then choose the name of the context and the path of the entities will be created in , and what do you want to generate , 
            // DBContext only or entities or both of them , also choose the naming , choose to use data annotations or the default which is
            // fluent apis , include connection string or not , install efcore provider when installing or not , using custom templete 
            // when creating code or not (C# T4 => self study) , and some advenced features ....
            // 
            // Note : the code generated by efcore power tools must not be edited (it's partial class) , because we can loose our edits 
            //        due to the re-generation of the code if we changed anything (we will edit in other partial class)


            // Read about : C# T4 templete code 


            // Some data annotations that we will learn and discuss :
            // 
            // [Index("CategoryId", Name = "CategoryID")]
            // [Column("ProductID")]
            // [Required]
            // [Column(TypeName = "money")]
            //
            // [ForeignKey("CategoryId")]
            // [InverseProperty("Products")]
            // public virtual Category Category { get; set; }


            // why do we use partial classes ? 
            // if we have the "partial class" of entity "Product" , and we want to add the ToString() method , we shouldn't edit and add 
            // in the "auto-generated" code of VS or EFCore power tools or any other generated code ... so we must make another file that 
            // has a new "file name" , but with the same class name and it must also be "partial class". This is my own partial class and 
            // i can add any code inside it without worrying of re-generation and loosing code i written.

            // See example in the Grid .... 


            // Note : the EFCore ".SaveChanges" is Transactional By default , means that if we have 3 statements and the last one failed then
            //        all of them will fail , BUT ADO is not Transactional by default , but can be achieved by making a transaction object 




            // Loading Types : 
            // 1 - Lazy Loading : retrieve only what is in the select (when trying to get navigational property data and it's null , then the
            //                    lazy loading DOES NOTHING)
            //
            // 2 - Eager Loading : using ".Include(x=>x.)" , specify what we exactly want and WE KNOW THAT WE WANT this. So we will join in 
            //                     the database and get the data of the navigational properties even if we didn't request their data in the
            //                     query. This will minimize the request of data from database (number of DB calls) , but if we don't need
            //                     this whole data it will be bad for memory (especially when the nav property is of type many "List" , ...)
            //
            // 3 - Explicit Loading : if we don't know if the nav property data is loaded or not so we can load it explicitly
            // 
            // 4 - Lazy Loading Proxies : same actions as Explicit Loading but without that much code ! (this was default in EF 6)
            //      - install package "Microsoft.EntityFrameworkCore.Proxies"
            //      - in DbContext class , in the OnConfiguration , make .UseLazyLoadingProxies()
            //    so now when trying to propagate and get data for a nav property AND WE KNEW THAT IT WAS NOT LOADED (IsLoaded == false) ,
            //    then we will load it , so incase of eager loading "for a specific nav property" then it will always be IsLoaded = true.
            //    it's the same as Explicit Loading with the same numbers of visiting DB , wihtout the two lines of (IsLoaded and Load).

            // 1. Lazy Loading : 
            var prds = (from P in context.Products
                        where P.UnitsInStock == 0
                        select P)                        // select only from the Product table (category and supplier are not shown)
                        // select P.ProductName)         // select only name from the Product table
                        // select new {name = P.ProductName, price = P.UnitPrice})         // select anonymous type from product table only
                        // select new {name = P.ProductName, category = P.Category.CategoryName})    // select anonymous type from 2 tables
                        .ToList();

            // so we will join and get data from other tables when only we tell in the query !
            // if we try to use prds in any other place it has the same data ! when querying the DB we didn't specify that we need the 
            // category and supplier data so the data of navigational properties didn't come. 


            // 2. Eager Loading : 
            var prds2 = (from P in context.Products.Include(p=>p.Supplier).Include(p=>p.Category)
                        where P.UnitsInStock == 0
                        // select P)                     // select only from the Product table (category and supplier are not shown)
                        // select P.ProductName)         // select only name from the Product table
                        // select new {name = P.ProductName, price = P.UnitPrice})         // select anonymous type from product table only
                        select new { name = P.ProductName, category = P.Category.CategoryName })      // select anonymous type from 2 tables
                        .ToList();

            foreach (var p in prds)
                Console.WriteLine(p);


            // Note : what if the nav property has a nav property inside it , or incase we have a many to many relationship and a Link
            //        table between the two tables ? we then use ".thenInclude(x=>x.)" , this means go one step further again 


            // 3 - Explicit Loading :
            //
            // how to know that we included the nav proeprties or no (to avoid problems later , if we don't remember the query that we wrote
            // or we are not the developers who wrote the query) (Disadvantages -> extra call to DB) :  .Reference()   or  .Collection()
            // Note :  .IsLoaded => it's in the memory , no need to go to DB  .....     .Load() => it's a trip to the DB , must go to load 
            //
            // - incase the navigational property is ONE  :
            //
            //     if( ! Context.Entry(obj).Reference(x=>x.NavPropertyName).IsLoaded )
            //              Context.Entry(obj).Reference(x=>x.NavPropertyName).Load()         // Explicit Loading 
            // - incase the navigational property is MANY : 
            //
            //     if( ! Context.Entry(obj).Collection(x=>x.NavPropertyName).IsLoaded )
            //              Context.Entry(obj).Collection(x=>x.NavPropertyName).Load()        // Explicit Loading 

            // Important Note : in the last code , it we Loaded the nav property data , IT WILL BE LOADED FOR THIS OBJECT AND ANY OBJECT 
            //                  HAVING THE SAME NAV PROPERTY DATA. OTHER OBJECTS HAVING A DIFFERENT NAV PROPERTY DATA WILL NOT BE LOADED FOR
            //                  THEM AND WE MUST CHECK LOAD IT WILL THE SAME WAY (EX: for a list of products , we must check for each product
            //                  in the list that it's supplier is loaded)

            // this is better that using obj.NavPropertyName == null , because it may be null in the DB and we now had an unnecessary call 
            // to the database and it will be null also ! 


            // so if we know 100% that we will need this data then include it , otherwise if MAY need the data then it's better to request 
            // them when needed 



            // -------------------------------------------------------------------------------------------------------------------------


            // Part 2 is "Code First" , it's in the "MyHospitalApp" , see notes there !
        }
    }
}
