using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;

namespace IKIA.BLL.Common.Services.Emails
{
	public class EmailService : IEmailService
	{
		private readonly IConfiguration _configuration;

		public EmailService(IConfiguration configuration)
        {
			_configuration = configuration;
		}


        // The email is sent from email that is on Email server , ex: Gmail , Yahoo , .... . Also some companies have their own email server
        // ex: Mahmoud.Shoura@microsoft.com
        public async Task SendAsync(string from, string recipients, string subject, string body)
		{
			// Bad , must be stored in the App Settings :
			// var senderEmail = "mahmoud.shoura@gmail.com";
			// var senderPassword = "P@ssw0rd123";
			
			var senderEmail = _configuration["EmailSettings:SenderEmail"];
			var senderPassword = _configuration["EmailSettings:SenderPassword"];
			
			
			// Note : we will notice that the password in the app setting must be generated by google , how ? 
			//        1 - allow 2 step verification 
			//        2 - search on "App Passwords"
			//        3 - Create a password and copy and paste it inside the ass settings
			
			
			var emailMessage = new MailMessage();
			emailMessage.From = new MailAddress(from);
			emailMessage.To.Add(recipients);
			// emailMessage.CC                        // send also the same email to .. 
			// emailMessage.Attachments
			emailMessage.Subject = subject;
			emailMessage.Body = body;
			// sometimes we notice that the body is HTML code ! how to do this ? 
			emailMessage.Body = $"<html><body><h2>{body}</h2></body></html>";
			emailMessage.IsBodyHtml = true;
			
			
			// Legacy old way , we will use a better way in the workshop ...
			var smtpClient = new SmtpClient(_configuration["EmailSettings:SMTPClientServer"], int.Parse(_configuration["EmailSettings:SMTPClientPort"]))  
			{
				// domain of the main server , Port (these are for gmail ! search)
				Credentials = new NetworkCredential(senderEmail, senderPassword),
				EnableSsl = true
			};      
			
			smtpClient.Send(emailMessage);






			// try
			// {
			// 	using (SmtpClient smtpClient = new SmtpClient(_configuration["EmailSettings:SMTPClientServer"], int.Parse(_configuration["EmailSettings:SMTPClientPort"]!)))
			// 	{
			// 		smtpClient.Credentials = new NetworkCredential(senderEmail,senderPassword);
			// 		smtpClient.EnableSsl = true;
			// 
			// 		MailMessage mail = new MailMessage
			// 		{
			// 			From = new MailAddress(from),
			// 			Subject = subject,
			// 			Body = "This is a test email."
			// 		};
			// 		mail.To.Add(recipients);
			// 
			// 		smtpClient.Send(mail);
			// 		Console.WriteLine("Email sent successfully!");
			// 	}
			// }
			// catch (SmtpException ex)
			// {
			// 	Console.WriteLine($"SMTP Error: {ex.Message}");
			// }



		}
	}
}
