using Talabat.Core;
using Talabat.Core.Entities.Order_Aggregate;
using Talabat.Core.Entities.Products;
using Talabat.Core.Repositories.Contract;
using Talabat.Core.Services.Contract;
using Talabat.Core.Specifications.Order_Specs;

namespace Talabat.Service
{
    public class OrderService : IOrderService
    {
        private readonly IBasketRepository _basketRepo;
        private readonly IUnitOfWork _unitOfWork;

        // Old Before using the Unit of Work 
        //
        // private readonly IGenericRepository<Product> _productRepo;
        // private readonly IGenericRepository<DeliveryMethod> _deliveryMethodsRepo;
        // private readonly IGenericRepository<Order> _orderRepo;
        public OrderService(IBasketRepository basketRepo, IUnitOfWork unitOfWork /*IGenericRepository<Product> productRepo */
            /*, IGenericRepository<DeliveryMethod> deliveryMethodsRepo , IGenericRepository<Order> orderRepo*/)
        {
            _basketRepo = basketRepo;
            _unitOfWork = unitOfWork;

            // _productRepo = productRepo;
            // _deliveryMethodsRepo = deliveryMethodsRepo;
            // _orderRepo = orderRepo;
        }

        public async Task<Order?> CreateOrderAsync(string buyerEmail, string basketId, int deliveryMethodId, Address shippingAddress)
        {
            // 1 - Get Basket from Baskets Repo
            // 2 - Get Selected Items at basket from Products repo
            // 3 - Calculate SubTotal
            // 4 - Get Delivery Method from DeliveryMethods repo
            // 5 - Create Order
            // 6 - Save to Database 

            var basket = await _basketRepo.GetBasketAsync(basketId);

            var orderItems = new List<OrderItem>();
            if (basket?.Items?.Count() > 0)
            {
                var productRepo = _unitOfWork.Repository<Product>();
                foreach (var item in basket.Items)
                {
                    var product = await productRepo.GetAsync(item.Id);
                    if (product != null)
                    {
                        var productItemOrdered = new ProductItemOrdered(product.Id, product.Name, product.PictureUrl);

                        var OrderItem = new OrderItem(productItemOrdered, product.Price, item.Quantity);
                        // Note : We take the price from the Product we got from the repo , not from the basket directly because the price can 
                        //        be changed ..

                        orderItems.Add(OrderItem);
                    }
                }
            }

            var subTotal = orderItems.Sum(order => order.Quantity * order.Price);

            var deliveryMethod = await _unitOfWork.Repository<DeliveryMethod>().GetAsync(deliveryMethodId);

            var order = new Order(buyerEmail, shippingAddress, deliveryMethod, orderItems, subTotal);
            // Notice the point we talked about "Not writing FK , and using navigational property only and EFCore will known automatically"
            // when we get the deliveryMethod from the database , it came with tracking and when making the Order object , the EFCore 
            // set the value of column FK (generated by EFCore , I commented it) = deliveryMethod.id

            // when making the order object , it's better to send the all object of delivery method instead of only sending the delivery 
            // method Id , that's because when we get the order the delivery method navigational property will = Null, we will have only
            // the FK delivery method Id ...


            // Now add the order in the repository 
            // But in the repository , we don't have "Add" or "Update" or "Delete" methods !! 
            // We will add them now in the generic repository interface and class

            await _unitOfWork.Repository<Order>().AddAsync(order);

            // After implementing the UnitOfWork : 

            var result = await _unitOfWork.CompleteAsync();

            if (result <= 0)
                return null;

            return order;


        }

        public async Task<IReadOnlyList<Order>> GetOrdersForUserAsync(string buyerEmail)
        {
            var ordersRepo = _unitOfWork.Repository<Order>();

            var specs = new OrderSpecifications(buyerEmail);
            var orders = await ordersRepo.GetAllWithSpecAsync(specs);

            return orders;

            // or
            // return await _unitOfWork.Repository<Order>().GetAllWithSpecAsync(new OrderSpecifications(buyerEmail));
        }
        public async Task<Order?> GetOrderByIdForUserAsync(int orderId, string buyerEmail)
        {
            var orderRepo = _unitOfWork.Repository<Order>();

            var specs = new OrderSpecifications(orderId,buyerEmail);

            var order = await orderRepo.GetWithSpecAsync(specs);

            return order;

            // or 
            // return await _unitOfWork.Repository<Order>().GetWithSpecAsync(new OrderSpecifications(orderId, buyerEmail));
        }

        public async Task<IReadOnlyList<DeliveryMethod>> GetDeliveryMethodsAsync()
            => await _unitOfWork.Repository<DeliveryMethod>().GetAllAsync();

    }
}
