namespace MyNotes
{
    internal static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            // To customize application configuration such as set high DPI settings or default font,
            // see https://aka.ms/applicationconfiguration.
            ApplicationConfiguration.Initialize();
            Application.Run(new Form1());
            Regions();
        }
        static void Regions()
        {
            // Now we are working with Windows form applications , a technology to produce a GUI that works with windows only , and has 
            // abit different code workflow 

            // when making a new windows form application project , we will find the program.cs class that has the main function , in the
            // main function we will find "Application.Run" , Application is the class that deals with the whole application we have , it 
            // takes a parameter of type form , and this is the main form with us , if it's closed and deleted (Disposed) then the whole
            // program will end , else if we go to another form then the program will continue until the the main form is closed , we can 
            // also terminate the program by "Application.Exit()"

            // So what is the Form class , it's a class that can be viewed in two places , first is the code .cs file (Partial class to make
            // it possable to separate the code generated by VS and the code written by us), second is the code .Designer.cs file (partial
            // class also that is generated by VS) , this .Designer.cs file has a function called "InitializeComponent" that has any
            // thing related to visuals, ex: size , ...... (it's not recomended to change any thing with code here in this class , as
            // with any change we do the file will be re-generated again when haing any visual change (ex: changing the size of the window))

            // last is the visual appear of the form , which is a .cs file [Design] , any thing that can be done with code can also 
            // be done with drag and drop , but drag and drop is better and easier. 

            // The form has attributes and properties , to see them => F4 (can be used with any object supports property window) , this
            // can show the "properties" and also "Events" , properties : font , Text (the word written in the header of the form) ,
            // foreColor , opacity , ... (properties can be shown as categorized or alphabetical)

            // Note : making any change in the properties reflect in the InitializeComponent function , that is a partial class and 
            //        re-generated at each time a change occures to the form

            // Note : the clientSize property is the available space to be customized by us.

            // Now the form is empty , we now should add controls to it , we can show the Toolbox from the "View" 

            // Note : the button is a class in System.Windows.Forms.Button , when putting a button in the form , this is a composotion
            //        relationship , so when making a new button in the form we see that in the ".Designer.cs" has a new attribute for 
            //        that button , and it's initialization is done in the InitializeComponent , with the basic properties ex: text , size , 
            //        name. 

            // Note : All object has the name property. 

            // Note : we must allow the object to appear in the form GUI (it's in the memory but not in the GUI), this is done by
            //        "this.Controls.Add(this.ObjectName);" in the InitializeComponent function. 

            // The button is a control which is in th BCL , it's xaml (XML)

            // in events : the publisher is the class "Form" , the subscriber is class "form1" or class name of the form. 

            // Event registeration : 
            // override the function of the event. Ex: OnResizeBegin(EventArgs e) { base.OnResizeBegin(e);  this.Opacity = 0.75 } 
            // this.ResizeBegin += (sender , e) => this.Opacity = 0.75

            // with buttons , the publisher is the "Button" , and the subscriber is the Form. 

            // if we double clicked on the button we will have 2 things : 
            // - A function will be created in the ".cs" file 
            // - The registeration of the event in the ".Designer.cs" file

            // so if we deleted the function that is created for the event , and didn't delete the event then we will have an error ... 
            // the event must be deleted from the ".Designer.cs" file first

            // Note : Anchor property for maintaining the placement (left and top edges by default) , we can change it to make it any 
            //        other combination ! 

            // the text box is multiline by default , we can make it one line , and we can make it stretches when changing the size of the 
            // form 

            // the text field has a property called PasswordChar , which we give the char for showing passwords when entering data.

            // Event when clicking the closeBTN to close the form : 
            // closeBTN.Click += (sender, e) => this.close();

            
            // inside the button called "Submit" in the Click event: 
            // if(txtUserName == "ABC" && txtPassword == "123")
            // {
            //     this.Hide();
            //     FrmHome.Show();        // must make an object first
            //     this.Visible = true;   // after closing the other form , the old one will be shown again 
            // }

            // .Show vs .ShowDialog : 
            // show we can see both forms , but showDialog when going to the new form we couldn't use the last form until finishing the 
            // new one first (couldn't change the focus) ... 

            // Dialog : component that cannot be designed 

            // now the assignment is making the same example in the video .... 
        }
    }
}