using NorthWindConsole.Context;

namespace NorthWindConsole
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // we will use EFCore Power Tools for making Views and SPs : 

            // -------------------------------
            // Views : 

            // How the view is mapped ? 
            // using Data Annotations :
            //   - use [Keyless] attribute
            // using Fluent APIs : 
            //   - entity.HasNoKey().ToView("Products by Category");
            //   - Note : we told the EF now that this is a view but we cannot insert, update, delete from it 


            // Note : Incase of working with code first and we wrote a DbSet for a view , then EFCore will not make that view or check it's
            // created or not !!! so we we must make it manually in the DB or put the code of creating the view inside the migration file.


            // when using the EFCore power tools we will find that we have a DbSet for the view , and the configuration is written to tell 
            // that this is a view and doesn't have a key , and also we will find a new Entity or models has the same name of the View , 
            // and this class represents the return type of the view 


            // -------------------------------
            // SPs : 

            // Stored Procedures : 
            // in case the return from the SP is a mapped entity then it's better to use the way we knew last session 
            // using one of the functions , but incase of SPs that do "Insert", "Update", "Delete" , or a not mapped entity then we 
            // can find an advantage for using Power Tools !
            //
            // ex: Sp that selects all products , actually the return is a mapped entity (product) , but EFCore Power tools will generate
            //     a new class for the return type (which is actually same as product class) so this is the bad thing happened ... for 
            //     mapped entities it's better to use the normal way for executing Sps known from previous session.



            // when using the EFCore power tools we will find that we have new DbContext class (other than the DbContext class for the
            // whole database) , that has async functions , each function represents a stored procedure and has the same name of it , these
            // functions execute raw SQL (see the implementation of them). 

            // to use these functions we must make an object of this contextProcedures class first that takes an object from the normal
            // context , and then we can use the functions that map the SPs for us ! 
            // note : normal context => Unmanaged resource , must use "using"
            // note : contextProcedures => managed resource and don't use "using"

            // using NorthwindContext context = new();
            // NorthwindContextProcedures procedures = new NorthwindContextProcedures(context);
            // 
            // var res = procedures.TenMostExpensiveProductsAsync().Result;
            // 
            // foreach (var item in res)
            // {
            //     Console.WriteLine(item.TenMostExpensiveProducts + " " + item.UnitPrice);
            // }
            // 
            // var result = procedures.UpdateProductPriceAsync(1, 105).Result;
            // Console.WriteLine($"{result} Rows affected");


            // Remember the Query Filter , how to change the way that delete works with ? 
            // for the entity , write fluent apis and "entity.DeleteUsingStoredProcedure()" and specify the name of the SP and the 
            // parameters it takes. 

            // We also have "InsertUsingStoredProcedure()" and "UpdateUsingStoredProcedure()"

            // Note : Remember to make another partial class other than the file generated by EFCore , so that it's not deleted later when
            //        editing using EFCore ! 


            // -------------------------------------------------------

            // Micro frameworks : Dapper 
            // We may use Dapper because it's better and faster than EFCore in some cases , and we don't want to go low level and use ADO
            // so we can use Dapper ! 

            // See Project : 
        }
    }
}
