using Microsoft.AspNetCore.Identity;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Net.Mail;
using System.Reflection;
using System.Reflection.Metadata;
using System.Threading.Channels;
using System.Xml.Linq;
using static System.Collections.Specialized.BitVector32;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace RegionsProject
{
    internal class Regions
    {
        static void Main(string[] args)
        {
            #region Self Study and Notes

            /* Start *****************************************************************************************************************/



            /* End ******************************************************************************************************************/

            #endregion


            #region Sending Emails by mailKit (New Way)

            /* Start *****************************************************************************************************************/

            // It's better than sending email by the default way of microsoft that was implemented in the last session 
            // We do the same steps for sending Emails or SMS messages ...

            // Steps : 
            // 1 - Add Email Settings in the "appsettings" file
            //     (Email , Display Name , Password [generated by google] , host [for gmail] , Port [That is deployed on it] )
            // 2 - Make a class with the same names of the properties to use them as : 
            //     builder.Services.Configure<NewEmailSettings>(builder.Configuration.GetSection("NewEmailSettings"));
            //     -- This is to be able to use it "Parameter -> IOptions<NewEmailSettings> options" , "field -> private readonly NewEmailSettings _options;"
            // 3 - install packages "mailKit" and "mimeKit" in the PL layer
            // 4 - Re-implement the old implementation in Account Controller (change the old service to the new service only)
            // 5 - Add services in Program class

            // Note : See the app settings 
            //        we use the same way we used to generate password in google last session

            // Note : See PL -> Emails ... this is the new implementation for Email Service       

            /* End ******************************************************************************************************************/

            #endregion


            #region Sending SMS by Twilio

            /* Start *****************************************************************************************************************/

            // Unfortunately it didn't work with me :) .... I coudn't get a number from twilio
            // but the implementation is right ... 

            // Twilio is not a free option !! 
            // We can also use any other service , such as : "Broadnet" , "SMSmisr" , "Cequens" , "Victory Link"

            // See appsettings
            // See PL -> SMS
            // install Twilio package
            // add the services in Program class
            // edit the account controller

            /* End ******************************************************************************************************************/

            #endregion


            #region External Login With Google

            /* Start *****************************************************************************************************************/

            // Unfortunately didn't work but i don't know why !! 


            // https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-9.0

            // First : https://console.cloud.google.com/apis/credentials
            // follow the steps in the video or in google
            // We want : Client ID , Client secret

            // see appsettings (add "Authentication")
            // install package "Microsoft.AspNetCore.Authentication.Google"
            // See program class
            // adding an action in the account controller

            /* End ******************************************************************************************************************/

            #endregion


            #region Search By Ajax Call

            /* Start *****************************************************************************************************************/

            // Unfortunately didn't work but i don't know why !! 

            // in the search of Employee index view ... 
            // in employee controller , make a new action called "Search" same as "Index" but returns a "PartialView"
            // make the partial view with the Table only
            // Note : the jquery script must be before render body ....
            // then write the Ajax code in the index view 
            // 

            /* End ******************************************************************************************************************/

            #endregion
        }
    }
}
